[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
path="src/lib_shared.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
shellexpand = "2"
thiserror = "1.0"