[package]
name = "encode"
version = "1.0.0"
edition = "2021"

[lib]
path="src/lib_encode.rs"

[dependencies]
base64 = "0.13.0"
html-escape = "0.2.11"
regex = "1.6.0"
serde = { version = "1", features = ["derive"] }
url = "2.3.1"
urlencoding = "2.1.2"

shared = { path = "../lib-shared" }