[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
path="src/lib_app.rs"

[dependencies]
float_eq = "1"
serde = { version = "1", features = ["derive"] }
shared = {path = "../lib-shared"}